services:
  pgadmin:
    image: dpage/pgadmin4:9.3.0
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      network_service:
        ipv4_address: 10.10.3.30 # 80
      network_db:
        ipv4_address: 10.10.2.10
    dns:
      - 10.10.3.200

networks:
  network_service:
    external: true
  network_db:
    external: true