services:
  julia:
    image: julia:local
    container_name: julia-maintainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - opt:/julia

volumes:
  opt:
    external: false